class Language {
  loadLanguage = () => {
    global.appLanguages = {
      en: {
        app_name: 'InfinitePower',
        logOut: 'Logout',
        login: 'Login',
        loginTab: 'Login',
        newAccount: 'Register',
        create: 'create',
        edit: 'edit',
        accountCreated: 'New account created.',
        email: 'Email',
        name: 'Name',
        password: 'Password',
        change_password: 'Change Password',
        repeat: 'Repeat Password',
        checkFields: 'Fill in all fields.',
        loginSuccess: 'session started successfully.',
        dontRemember: 'Forgot your password?',
        google: 'Login With Google',
        facebook: 'Login With Facebook',
        guest: 'Use Without Login',
        settings: 'Settings',
        mainColor: 'Main Color',
        change: 'Change',
        mainTheme: 'Main Theme',
        white: 'White',
        black: 'Dark',
        text: 'Text',
        lan: 'Language',
        language: 'English',
        hello: 'Hello',
        register: 'Register',
        enter: 'Enter',
        save: 'Salvar',
        never: 'Never',
        sometimes: 'Sometimes',
        always: 'Always',
        understood: 'Understood',

        //message type
        msg_err_connect: 'Connection failed.',
        there_is_a_connection_problem: 'Connecion problems.',
        msg_warn_fieldsfill: 'Complete all fields to continue',
        msg_no_video: 'No Video to display',
        msg_success_wallpaper_uploading: 'Uploaded wallpaper successfully. ',
        msg_downloading: 'Downloading..',
        msg_loading: 'Loading..',
        msg_add_impossible: 'Routine can not contain more than 5 phrases.',
        msg_no_routine: 'No routine to display',
        msg_no_tip_content: 'There is no information to show.',
        msg_no_routine_to_play: 'There is no phrase to play',
        msg_fail_upload: 'Uploading file failed.',
        msg_saved_result: 'Saved Routine Successfully',
        msg_saved_affirmation: 'Affirmation saved successfully',
        msg_failed_saving: 'Routine save failed.',
        msg_downloading_image: 'Downloading image ...',
        msg_downloading_phrase: 'Downloading Phrases',
        msg_removed_success: 'Successfully removed',
        msg_removed_failed: 'Routine remove failed.',
        msg_err_fill_information: 'You should select at least one day.',
        msg_error_custome: 'Normal affirmation can`t be mixed with custom.',
        //title section
        title_information: 'INFORMATION',
        title_add_phrases: 'Add Phrases',
        title_wishlist: 'MY FAVOURITE PHRASES',
        title_achievement: 'MADE',
        title_capsule: 'CAPSULES',
        schedule: 'schedule',
        title_rountine_schedule: 'ROUTINE SCHEDULE',
        title_new_affairmations: 'new affirmations',
        title_my_routine: 'MY ROUTINE',
        title_whishList: 'WhishList',
        title_my_routines: 'MY ROUTINES',
        title_setting: 'SETTING',
        title_select_font: 'font size',
        title_adv_config: 'Advanced configuration',
        //strings for app inside
        replace_msg1: 'The limit of statements in a routine is 5, please uncheck',
        replace_msg2: ' to continue',
        musical_affirmations: 'Musical affirmations',
        background_mode: 'Enable background image',
        sleep_mode: 'Sleep mode',
        random: 'Random',
        repeated: 'Repeated',
        selectforaffair: 'Select for affirmation',
        replacePhrase: 'Replace an phrase ',
        choosewallpaper: '+Choose a wallpaper to reproduce',
        selectbyroutine: 'Select By Routine',
        title_consecutive_weeks: 'SUCCESSFUL \r\n CONSECUTIVE WEEKS',
        title_last_three_weeks: 'ACTIVITY LAST 3 WEEKS',
        title_last_twelve_weeks: 'ACTIVITY LAST 12 WEEKS',
        title_average_three_weeks: 'AVERAGE LAST 3 WEEKS',
        title_routine_lists: 'Routine List',
        title_choose_routine: 'Choose a routine',
        title_video_list: 'Video List',
        label_inser_name: 'Insert new name',
        create_routine: 'New Routine',
        edit_routine_name: 'Edit routine name',
        title_video: 'Video',
        title_improvement: 'PERSONAL \r\n IMPROVEMENT PLAN',
        title_evaluation: 'EVALUATION PAGE',
        title_statistic: 'STATISTIC',
        title_current_activity: 'CURRENT ACTIVITY',
        title_song_affirmation: 'SONG AFFIRMATION',
        //menu strings
        menu_made: 'Affirmations Made',
        //label strings
        label_routine_full: 'The routine is full',
        label_improvement: 'PERSONAL IMPROVEMENT PLAN',
        label_objective: 'OBJECTIVE',
        label_trigger: 'TRIGGER',
        label_tester: 'TESTER',
        label_auto_evaluation: 'AUTO EVALUATION',
        label_frequency: 'FREQUENCY EVALUATION',
        label_deadline: 'DEADLINE',
        label_objectiveof: 'OBJECTIVE OF',
        label_achieve: 'ACHIEVE',
        label_not_achieve: 'NOT ACHIEVED',
        label_send: 'SEND',
        label_no_evaluation: 'I HAVE NO \r\n EVALUATION TODAY',
        label_evaluation_schedule: 'EVALUATION \r\n SCHEDULE',
        label_no_evaluation_schedule: 'NO MORE \r\n EVALUATING',
        label_today: 'TODAY',
        label_total_duration: 'Total duration of the routine',
        label_number_repetition: 'Repetitions for each affirmations',
        label_duration_pause: 'Duration of pauses in seconds',
        label_repeat: 'Repetir',
        label_time_routine: 'Routine time',
        label_music: 'Musics',
        label_tones: 'Tones',
        label_mode: 'Mode',
        label_tiempo: 'Time',
        label_background_image: 'Background images',
        label_others: 'Others',
        label_add_reminder: '+ Add Reminder',
        label_search: 'Search',
        label_advanced_configuration: 'Advanced Configuration',
        label_adjust_time: 'Adjust Time',
        label_save: 'Save',
        label_update: 'Update',
        label_categories: 'Categories',
        label_pre_armed: 'Pre-Armed',
        label_satisfaction_need: 'Satisfaction of Need / Desire',
        label_personalizadas: 'Custom',
        label_customize_affirmation: 'Customize affirmation',
        label_reminder: 'Reminder',
        label_favorite_phrase: 'Favourite Phrases',
        label_affirmation_made: 'Made Affirmations',
        label_routine_schedule: 'Routine Schedule',
        label_create_affirmation: 'Create New Affirmation',
        label_warning: 'Warning',
        label_create_new_routine: 'Create New Routine',
        label_today_schedule: `TODAY'S SCHEDULE`,
        //label for main
        label_size: 'Size',
        close: 'close',
        label_select: 'Select',
        label_summery_day: 'SUMMERY OF THE DAY',
        resources: 'resources',
        label_reproductions: 'REPRODUCTIONS',
        label_minutes_done: 'MINUTES DONE',
        label_average: 'AVERAGE',
        label_activity_3_weeks: 'ACTIVITY LAST 3 WEEKS',
        activity: 'activity',
        label_3_weeks: '3 WEEKS',
        label_successful: 'SUCCESSFUL',
        label_consecutive_weeks: 'CONSECUTIVE WEEKS',
        label_blockage_of: 'BLOCKAGE OF',
        label_negative_thought: 'NEGATIVE THOUGHT',
        label_total: 'TOTAL',
        label_attention: 'ATTENTION',
        label_successful_consecutive: 'SUCCESSFUL CONSECUTIVE WEEKS',
        label_blockage: 'BLOCKAGE OF NEGATIVE THOUGHT',
        label_total_attention: 'TOTAL ATTENTION',
        mental_focusing: 'mental focusing',
        meditation: 'meditation',
        label_action: 'action',
        label_tips: 'TIPS',
        label_informations: 'INFORMATIONS',
        label_videos: 'VIDEOS',
        label_never: 'NEVER',
        label_sometimes: 'SOMETIMES',
        label_always: 'ALWAYS',
        label_do_excercise: 'DO EXCERCISE',
        label_exercise: 'EXERCISE',
        label_conscience: 'CONSCIENCE',
        label_practice: 'PRACTICE',
        label_awareness: 'AWARENESS',
        label_training: 'TRAINING',
        label_application: 'APPLICATION',
        label_routine: 'Add To Routine',
        label_new_routine: 'Add To New Routine',
        label_add_affirmation: 'Add affirmation',
        label_performed: 'Add To Performed',
        label_reorder_routines: 'Reorder routines',
        label_wishes: 'Add To Wishes',
        label_edit: 'Edit',
        label_remove: 'Remove',
        label_remove_image: 'Remove image',
        cancel: 'Cancel',
        label_add_to_achievements: 'Add to Performed',
        label_background_title: 'Background image for routine',
        label_error: 'Error',
        unexpected_error: 'Unexpected error',
        label_volume: 'Volume',
        of: 'of',
        label_white_belt: 'WHITE BELT',
        label_complete: 'complete',
        label_success_consecutive: 'successful consecutive',
        label_weeks_to_reach: 'weeks to reach',
        label_yellow_belt: 'YELLOW BELT',
        label_actual_belt: 'Actual Belt',
        label_green_belt: 'Green Belt',
        label_black_belt: 'Black Belt',
        label_master_black_belt: 'Master Black Belt',
        label_delete: 'Delete',
        label_affirmation: 'Affirmation',
        label_gratitude: 'Gratitude',
        label_next: 'Next',
        label_addto_myroutine: 'Add to my routine',
        label_show_status: 'Show status',
        label_good_morning: 'Good Morning',
        label_good_afternoon: 'Good Afternoon',
        label_good_evening: 'Good Evening',
        label_good_night: 'Good Night',
        label_change_name_title: 'Change name',
        label_regisered_since: 'Registered Since',
        label_language: 'Language',
        label_notification: 'Notifications',
        label_support: 'Support',
        label_clear_session: 'Close Session',
        label_comments: 'Comments',
        //statements
        state_tester: 'Select one or more you want to be part of your progress , evaluate yourself,or to do both',
        //info dialog
        dialog_background: 'It will display the background image you have selected in the advanced settings of your routine.',
        dialog_sleep:
          'The volume of the statements will gradually decrease. You can sleep listening to the music, but the statements will still be noticeable to your subconscious.',
        dialog_random: 'Your affirmations will be played randomly. Active random: 1,2,3, ...; 1,2,3, ... Random inactive: 1,1,1, ...; 2,2,2, ...',
        dialog_repeate: 'When your workout ends, it will play again once more.',
        generate_note: 'Generate Note',
        evaluate_target: 'Evaluate an target',
        create_edit_target: 'Create or edit a target ',
        progress: 'View progress',
        my_objectives: 'my objetives',
        agree_share_results: 'If you agree that your evaluators see your progress, activate sharing results:',
        active_routine: 'Routine created',
        deactive_routine: 'Inactive routine',
        active_routine_days: 'days ago',
        yesterday: 'yesterday',
        day_monday: 'Monday',
        day_tue: 'Tuesday',
        day_wed: 'Wednesday',
        day_th: 'Thursday',
        day_fri: 'Friday',
        day_sat: 'Saturday',
        day_sun: 'Sunday',
        results: 'Results',

        monday: 'monday',
        tuesday: 'tuesday',
        wednesday: 'wednesday',
        thursday: 'thursday',
        friday: 'friday',
        saturday: 'saturday',
        sunday: 'sunday',

        action_objective: 'Objective',
        action_description: 'Description',
        action_trigger: 'Trigger',
        action_deadline: 'Deadline',
        action_evaluation_days: 'Evaluation days',
        edited_success: 'Edited successfully',
        edited_error: 'Can not edit the objective',
        delete_objective_success: 'Objective deleted',
        delete_objective_error: 'Can not delete objective',
        delete_objective_warning: 'Are you sure you want to delete the objective?',
        who_evaluate: 'People I evaluate',
        evaluating: 'I am evaluating the objectives of',
        evaluating_to: 'I am evaluating to',

        title_objective: 'The objective',
        include_note: 'Include note',

        label_objectives: 'Objectives',
        create_objective: 'Define a new objective',
        placeholder_objective: 'Select title to your objective',
        placeholder_description: 'This is and optional field.If you want you can be more specific detailing your objective.',
        placeholder_trigger:
          'This is and optional field.All the habits,good or bad,has a trigger that origined.Identify which is will plus your chances to reach your objective.',
        days_subtitle: 'Evaluation days',
        deadline_subtitle: 'What is the deadline for acheiving your objective?',

        tester_statement: ' Do want to evaluate yourself?.',
        auto_evaluation: 'self evaluation',
        evaluation: 'evaluation',
        title_share_statement: 'You can also invite people you trust to be part of your progress as evaluators. To do this, share this code:',
        label_share: 'Share',
        share_statement: ' If you will have evaluators,do you want that person see the result?',
        title_share_results: 'Share results',
        label_share_results: 'If you agree that your evaluators see your progress, activate sharing results:',
        create_objective_success: 'Objective created successfully',
        save_objective_success: 'Objective saved successfully',
        save_objective_error: 'El proceso fallo',
        schedule_evaluations: 'Schedule Evaluations',
        achieve: 'Achieve',
        label_consistent: 'Consistent',
        not_consistent: 'Not Consistent',
        consistency: 'Consistency',
        obs_achieved: 'Archieved',
        obs_not_achieved: 'Not achieved',
        obs_not_evaluated: 'Not evaluated',
        bottom_statement: 'For your progress to be consistent, at least 75% of scheduled assessments must be completed.',
        add_friend_code: 'Use invite code',
        friend_code: 'Enter friend code',
        label_friend_code: 'Invite code',
        atention: 'Atention',
        label_atention: 'Atention',
        label_block: 'Block',
        label_perception: 'Perception',

        label_new_article_notification: 'New article available for read',

        label_new_objective_from_habit: 'Convert to action objective',

        label_notes: 'Notes',
        no_notes: 'No notes',
        label_never_show_again: 'Never show again',
        spanish: 'Spanish',
        english: 'English',
        action_share_title: 'Evaluate my progress in Infinite Power',
        action_share_message:
          'I invite you to evaluate my progress in Infinite Power! Download the application and access with the following link: infinitepower://code',
        ready: 'ready',
        copy_code: 'Copy code',
        evaluate: 'Evaluate',
        see_details: 'See details',
        note_created_successfully: 'Note created successfully',
        objective_evaluated_successfully: 'Objective evaluated successfully',
        note_created_successfully: 'Note created successfully',
        objective_updated_successfully: 'Objective updated successfully',
        no: 'No',
        no_date: 'No Date',
        required: 'Required',
        all_day: 'All days',
        guide_for_answers: 'Guide for answers',
        focusing_questionary: 'focusing questionary',
        no_data: 'No data',
        block_negative_thoughts: 'Block Negative Thoughts',
        atention_and_concentration: 'Atention and Concentration',
        perception_improvement: 'Perception Improvement',
        never: 'Never',
        almost_never: 'Almost Never',
        occasionally: 'Occasionally',
        frequently: 'Frequently',
        very_frequently: 'Very Frequently',
        send_response: 'Send Response',
        accept: 'Accept',
        user_name: 'User Name',
        to_your_account: 'to your account',
        and_enjoy_all_the_advantages: 'And enjoy all the advantages',
        offers_you: 'offers you',
        forget_password: 'Forget Password',
        sign_in: 'Sign In',
        log_in: 'Log In',
        user_registered_successfully: 'User registered successfully',
        meditation_tips: 'Meditation Tips',
        action_tips: 'Actions Tips',
        answers_were_sended_successfully: 'Answers were sended successfully',
        mental_focus: 'mental focus',
        i_am_ready: 'i am ready',
        get_in_ready: 'get in ready',
        recording: 'recording',
        playing: 'playing',
        habits: 'habits',
        habit: 'habit',
        consecutive_successful_weeks: 'consecutives successful weeks',
        view_tips_on: 'view tips on',
        convert_to_habit: 'convert to habit',
        delete_phrase_warning: 'Are you sure you want to delete the phrase?',
        deleted_correctly: 'deleted correctly',
        created_correctly: 'created correctly',
        saved_correctly: 'Saved correctly',
        affirmation: 'affirmation',
        affirmation_saved_as_draft: 'Affirmation saved as draft. You must record audios to play it in your routine.',
        unexpected_error_recording: 'unexpected error recording',
        notice: 'notice',
        habits_tips: 'habits tips',
        affirmations_categories: 'add affirmations',
        category: 'category',
        you_will_receive_a_reminder_at: 'You will receive a reminder at',
        select_time: 'select time:',
        confirm: 'confirm',
        last_21_days: 'last 21 days',
        january: 'january',
        february: 'february',
        march: 'march',
        april: 'april',
        may: 'may',
        june: 'june',
        july: 'july',
        august: 'august',
        september: 'september',
        october: 'october',
        november: 'november',
        december: 'december',
        focus: 'focus',
        today_activities: 'today activities',
        info: 'info',
        day_resume: 'day resume',
        write_note: 'write note',
        to: 'to',
        select_a_image: 'select a image',
        take_photo: 'take photo',
        choose_from_library: 'choose from library',
        choose: 'choose',
        show_more_notes: 'show more notes',
        show_less_notes: 'show less notes',
        write_a_final_comment_before_evaluate: 'write a final comment',
        focus_test: 'focus test',
        infinitepower_note: 'infinite power note',
        show_image: 'show image',
        show_notes: 'show notes',
        hide_notes: 'hide notes',
        today: 'today',
        achievement: 'achievement',
        last_7_days_achievements: 'last 7 days achievements',
        last_7_evaluations_achievements: 'last 7 evaluations achievements',
        streak: 'streak',
        day_results_for_objective: 'day results for objective',
        objective_average_achievement: 'objective average achievement',
        default_evaluations: 'default evaluations',
        evaluations_not_carried_out_are_considered_as_not_achieved: 'evaluations not carried out are considered as not achieved',
        my_routines: 'my routines',
        evaluations_all_days: 'evaluations all days.',
        evaluate_all_days: 'evaluate all days.',
        evaluate: 'evaluate',
        all_days: 'all days',
        on: 'on',
        evaluations: 'evaluations',
        achievements: 'achievements',
        current_streak: 'current streak',
        historical_streak: 'historical streak',
        how_they_evaluated_me: 'how they evaluated me',
        objective_defined_at: 'objective defined at',
        day: 'day',
        days: 'days',
        active: 'active',
        friends_objectives: 'friends objectives',
        pick_a_date: 'pick a date',
        days_left: '$days days left',
        pick_a_time: 'pick a time',
        the_field_is_required: 'the field is required',
        objective_title: 'objective title',
        objective_description: 'objective description',
        objective_description_placeholder:
          'This is an optional field. You can use it to describe the objective in more detail or its benefits or what or who inspired you to define it',
        habit_trigger_to_replace: 'habit trigger to replace',
        trigger_placeholder:
          'Optional field. The habits you want to replace have a trigger that activates them. Identifying it increases your chances of eliminating it',
        limit_date: 'limit date',
        evaluation_days: 'evaluation days',
        evaluators: 'evaluadores',
        evaluation_days_reminder: 'evaluation days reminder',
        confirmation: 'confirmation',
        are_you_sure_about_delete: 'you are sure you want to proceed with the removal?',
        code: 'code',
        enter_code: 'enter code',
        unfollowed_correctly: 'unfollowed correctly',
        reject: 'reject',
        invitation: 'invitation',
        has_invited_you_to_evaluate_the_objective: 'has invited you to evaluate the objective',
        objective_added_for_evaluation: 'objective added for evaluation',
        you_are_already_a_evaluator: 'you are already an evaluator',
        date_for: 'corresponding to',
        belt_info_title: 'consecutive weeks achieved',
        belt_info_title1: 'consecutive successful weeks',
      },
      es: {
        app_name: 'InfinitePower',
        logOut: 'Wyloguj się',
        login: 'Zaloguj się',
        loginTab: 'Logowanie',
        newAccount: 'Nowe konto',
        create: 'crear',
        edit: 'editar',
        accountCreated: 'Stworzono nowe konto.',
        email: 'Email',
        name: 'Imię',
        password: 'Contraseña',
        change_password: 'Cambiar contraseña',
        repeat: 'Powtórz hasło',
        checkFields: 'Sprawdź wszystkie pola.',
        loginSuccess: 'sesión iniciada correctamente.',
        dontRemember: 'Nie pamiętasz hasła?',
        google: 'Zaloguj się z Google',
        facebook: 'Zaloguj się przez Facebook',
        guest: 'Używaj bez logowania',
        settings: 'Ustawienia',
        mainColor: 'Główny kolor',
        change: 'Zmień',
        mainTheme: 'Główny motyw',
        white: 'Biały',
        black: 'Ciemny',
        text: 'Tekst',
        lan: 'Język',
        language: 'Polski',
        hello: 'Witaj',
        register: 'Registrar',
        enter: 'Entrar',
        never: 'Nunca',
        sometimes: 'A veces',
        always: 'Siempre',
        understood: 'Entendido',

        //Error Messages
        msg_err_connect: 'La conexion fallo.',
        there_is_a_connection_problem: 'Hay un problema con la conexion.',
        msg_warn_fieldsfill: 'Complete all fields to continue',
        msg_no_video: 'No Video to display',
        msg_success_wallpaper_uploading: 'Fondo de pantalla cargado con éxito.',
        msg_downloading: 'Descargando..',
        msg_loading: 'Cargando..',
        msg_add_impossible: 'La rutina no puede contener más de 5 frases.',
        msg_no_routine: 'No hay rutina para mostrar',
        msg_no_tip_content: 'No hay información para mostrar.',
        msg_no_routine_to_play: 'No hay frase para jugar.',
        msg_fail_upload: 'no se pudo cargar el archivo.',
        msg_saved_result: 'Rutina guardada con éxito',
        msg_failed_saving: 'La rutina de guardar falló.',
        msg_downloading_image: 'Descargando imagen ...',
        msg_downloading_phrase: 'Descargando frases ..',
        msg_removed_success: 'Eliminado con éxito..',
        msg_removed_failed: 'La eliminación rutinaria falló..',
        msg_err_fill_information: 'Debes seleccionar al menos un día',
        msg_saved_affirmation: 'Afirmación guardada con éxito',
        msg_error_custome: 'La afirmación normal no se puede mezclar con Personalizada.',
        //title section
        title_information: 'INFORMACIÓN',
        title_add_phrases: 'Agregar Frases',
        title_wishlist: 'MIS FRASES FAVORITAS',
        title_achievement: 'HECHO',
        title_capsule: 'CÁPSULAS',
        schedule: 'programación',
        title_my_routine: 'MI RUTINA',
        title_whishList: 'Lista de Deseos',
        title_my_routines: 'MIS RUTINAS',
        title_rountine_schedule: 'HORARIO DE RUTINA',
        title_new_affairmations: 'nuevas afirmaciones',
        title_consecutive_weeks: 'EXITOSO \r\n SEMANAS CONSECUTIVAS',
        title_last_three_weeks: 'ACTIVIDAD LAS ÚLTIMAS 3 SEMANAS',
        title_last_twelve_weeks: 'ACTIVIDAD LAS ÚLTIMAS 12 SEMANAS',
        title_average_three_weeks: 'PROMEDIO ÚLTIMAS 3 SEMANAS',
        title_choose_routine: 'Elige una rutina',
        title_video: 'Vídeo',
        title_improvement: 'PLAN DE \r\n MEJORA PERSONAL',
        title_evaluation_page: '',
        title_statistic: 'ESTADIDTICAS',
        title_current_activity: 'ACTIVIDAD ACTUAL',
        title_song_affirmation: 'AFIRMACIÓN DE CANCIONES',
        label_today: 'HOY',
        title_setting: 'Configuración general',
        title_select_font: 'Tamaño de fuente',
        title_adv_config: 'Configuración avanzada',
        //strings for app inside
        replace_msg1: 'El límite de las afirmaciones en una rutina es 5, favor desmarca',
        replace_msg2: ' para continuar',
        musical_affirmations: 'Afirmaciones Musicales',
        background_mode: 'Activar imagen de fondo',
        sleep_mode: 'Modo dormir',
        random: 'Aleatorio',
        repeated: 'Repetido',
        selectforaffair: 'Seleccionar para afirmación',
        replacePhrase: 'Reemplazar una frase',
        selectbyroutine: 'Seleccionar por rutina',
        choosewallpaper: '+Elige un fondo de pantalla para reproducir',
        save: 'guardar',
        title_routine_lists: 'Lista de rutina',
        create_routine: 'Nueva rutina',
        edit_routine_name: 'Editar nombre de rutina',
        menu_made: 'Afirmaciones Realizadas',
        title_video_list: 'Lista de videos',
        label_inser_name: 'Ingrese el nuevo nombre',
        //label strings
        label_routine_full: 'La rutina esta llena',
        label_improvement: 'PLAN DE MEJORA PERSONAL',
        label_objective: 'OBJETIVO',
        label_trigger: 'DESENCADENAR',
        label_tester: 'ENSAYADOR',
        label_auto_evaluation: 'AUTO EVALUATION',
        label_frequency: 'EVALUACIÓN AUTOMÁTICA',
        label_deadline: 'FECHA LÍMITE',
        label_objectiveof: 'OBJETIVO DE',
        label_achieve: 'LOGRAR',
        label_not_achieve: 'NO LOGRADO',
        label_send: 'ENVIAR',
        label_no_evaluation: 'NO TENGO EVALUACIÓN HOY',
        label_evaluation_schedule: 'PROGRAMA DE EVALUACIÓN',
        label_no_evaluation_schedule: 'NO MÁS EVALUACIÓN',
        label_total_duration: 'Duración total de la rutina.',
        label_number_repetition: 'cantidad de repeticiones por cada afirmacion',
        label_duration_pause: 'Duracion de pauses en segundos',
        label_repeat: 'Repetir',
        label_time_routine: 'Tiempo de rutina',
        label_music: 'Musicas',
        label_tones: 'Tonos',
        label_mode: 'Mode',
        label_tiempo: 'Tiempo',
        label_background_image: 'Imagenes de fondo',
        label_others: 'Otros',
        label_add_reminder: '+ Agregar Recordatorio',
        label_search: 'Buscar',
        label_advanced_configuration: 'Configuracion Avanzada',
        label_adjust_time: 'Ajustar Tiempo',
        label_save: 'Guardar',
        label_update: 'Actualizar',
        label_reminder: 'Recogdatoris',
        label_favorite_phrase: 'Frases Favoritas',
        label_affirmation_made: 'Afirmaciones hechas',
        label_routine_schedule: 'Agendamiento de Rutina',
        label_create_affirmation: 'Crear Nueva Afirmacion',
        label_create_new_routine: 'Crea una Nueva Rutina',
        label_warning: 'Advertencia',
        label_affirmation: 'Afirmación',
        label_gratitude: 'Gratitud',
        label_next: 'Siguiente',
        //label for main
        label_size: 'Talla',
        close: 'cerrar',
        label_select: 'Seleccionar',
        label_summery_day: 'RESUMEN DEL DIA',
        resources: 'recursos',
        label_reproductions: 'REPRODUCCIONES',
        label_minutes_done: 'MINUTOS HECHOS',
        label_average: 'PROMEDIO',
        label_activity_3_weeks: 'ACTIVIDAD LAS ÚLTIMAS 3 SEMANAS',
        activity: 'actividad',
        label_3_weeks: '3 SEMANAS',
        label_successful: 'EXITOSO',
        label_consecutive_weeks: 'SEMANAS CONSECUTIVAS',
        label_blockage_of: 'BLOQUEO DE',
        label_negative_thought: 'PENSAMIENTO NEGATIVO',
        label_total: 'TOTAL',
        label_attention: 'ATENCIÓN',
        label_action: 'acción',
        label_successful_consecutive: 'SEMANAS CONSECUTIVAS EXITOSAS',
        label_blockage: 'BLOQUEO DE PENSAMIENTO NEGATIVO',
        label_total_attention: 'ATENCION TOTAL',
        mental_focusing: 'enfoque mental',
        meditation: 'meditación',
        label_tips: 'CONSEJOS',
        label_informations: 'INFORMACIONES',
        label_videos: 'VIDEOS',
        label_never: 'NUNCA',
        label_sometimes: 'A VECES',
        label_always: 'SIEMPRE',
        label_do_excercise: 'HACER EJERCICIO',
        label_exercise: 'EJERCICIO',
        label_categories: 'Categorias',
        label_pre_armed: 'Pre-Armados',
        label_satisfaction_need: 'Satisfacción de Necesidad / Deseo',
        label_personalizadas: 'Personalizado',
        label_customize_affirmation: 'Personalizar afirmación',
        label_conscience: 'CONCIENCIA',
        label_practice: 'PRÁCTICA',
        label_awareness: 'CONCIENCIA',
        label_training: 'FORMACIÓN',
        label_application: 'FORMACIÓN',
        label_routine: 'Agregar a Rutina',
        label_new_routine: 'Agregar a nueva rutina',
        label_add_affirmation: 'Agregar afirmación',
        label_performed: 'Agregar a Realizadas',
        label_reorder_routines: 'Reordenar rutinas',
        label_wishes: 'Agregar a Deseos',
        label_edit: 'Editar',
        label_remove: 'Quitar',
        label_remove_image: 'Eliminar imagen',
        cancel: 'Cancelar',
        label_add_to_achievements: 'Agregar a Realizadas',
        label_background_title: 'Imagen de fondo de la rutina',
        label_error: 'Error',
        unexpected_error: 'Error inesperado',
        label_volume: 'Volumen',
        of: 'de',
        label_white_belt: 'CINTURÓN BLANCO',
        label_complete: 'completar',
        label_success_consecutive: 'exitoso consecutivo',
        label_weeks_to_reach: 'semanas para llegar',
        label_delete: 'Retirar',
        label_today_schedule: 'PROGRAMMACION DE HOY',
        label_addto_myroutine: 'Añadir a mi rutina',
        label_show_status: 'Mostrar estado',
        label_good_morning: 'Buen Dia',
        label_good_afternoon: 'Buenas Tardes',
        label_good_evening: 'Buenas Tardes',
        label_good_night: 'Buenas Noches',
        // label_weeks_to_reach : 'semanas ',
        label_yellow_belt: 'Cinturón Amarillo',
        label_actual_belt: 'Cinturón Real',
        label_green_belt: 'Cinturón Verde',
        label_black_belt: 'Cinturón Negra',
        label_master_black_belt: 'Cinturón negro maestro',
        label_regisered_since: 'Registrado desde',
        label_change_name_title: 'Cambiar de nombre',
        label_language: 'Idioma',
        label_notification: 'Notificación',
        label_support: 'Soporte',
        label_clear_session: 'Cerrar Sesión',
        label_comments: 'Comentarios',
        //statements
        state_tester: 'Seleccione uno o más que quiera ser parte de su progreso, evalúese a sí mismo o haga ambas cosas.',
        //info dialog
        dialog_background: 'Mostrará la imagen de fondo que hayas seleccionado en la configuración avanzada de tu rutina.',
        dialog_sleep:
          'El volumen de las afirmaciones bajará gradualmente. Podrás dormir escuchando la música, pero las afirmaciones seguirán siendo perceptibles para tu subconsciente.',
        dialog_random: 'Tus afirmaciones se reproducirán aleatoriamente. Aleatorio activo: 1,2,3,...; 1,2,3,... Aleatorio inactivo: 1,1,1,...; 2,2,2,...',
        dialog_repeate: 'Cuando finalice la reproducción de tu rutina, esta se reproducirá nuevamente una vez más.',

        generate_note: 'Generar Nota',
        evaluate_target: 'Evaluar un objetivo',
        create_edit_target: 'Crear o editar un objetivo ',
        progress: 'Ver progreso',
        my_objectives: 'mis objetivos',
        agree_share_results: 'Si estas de acuerdo en que tus evaluadores vean tu progreso, activa compartir resultados:',
        active_routine: 'Rutina creada hace',
        deactive_routine: 'Rutina inactiva hace',
        active_routine_days: 'días',
        yesterday: 'ayer',
        day_monday: 'Lunes',
        day_tue: 'Martes',
        day_wed: 'Miercoles',
        day_th: 'Jueves',
        day_fri: 'Viernes',
        day_sat: 'Sabado',
        day_sun: 'Domingo',
        results: 'Resultados',

        monday: 'lunes',
        tuesday: 'martes',
        wednesday: 'miercoles',
        thursday: 'jueves',
        friday: 'viernes',
        saturday: 'sabado',
        sunday: 'domingo',

        action_objective: 'Objetivo',
        action_description: 'Descripción',
        action_trigger: 'Disparador',
        action_deadline: 'Fecha final',
        action_evaluation_days: 'Dias de evaluación',
        edited_success: 'Editado correctamente',
        edited_error: 'No se pudo editar',
        delete_objective_success: 'Objetivo borrado',
        delete_objective_error: 'No se pudo borrar el objetivo',
        delete_objective_warning: 'Desea eliminar el objetivo?',
        who_evaluate: 'Personas a quien evalúo',
        evaluating: 'Yo estoy evaluando los objetivos de',
        evaluating_to: 'Yo estoy evaluando a',

        title_objective: 'El objetivo',
        include_note: 'Incluir nota',

        label_objectives: 'Objetivos',
        create_objective: 'Define un nuevo objetivo',
        placeholder_objective: 'Seleccionar el título de tu objetivo',
        placeholder_description: 'Este es un campo opcional. Si lo desea, puede ser más específico detallando su objetivo.',
        placeholder_trigger:
          'Este es un campo opcional. Todos los hábitos, buenos o malos, tienen un desencadenante que se originó. Identifique cuál será más sus posibilidades de alcanzar su objetivo.',
        days_subtitle: 'Días de evaluación',
        deadline_subtitle: '¿Cuál es la fecha límite para alcanzar su objetivo?',

        tester_statement: '¿Quieres evaluarte a ti mismo?',
        auto_evaluation: 'Autoevaluación',
        evaluation: 'evaluación',
        title_share_statement:
          'También puedes invitar a personas de tu confianza para que formen parte de tu progreso como evaluadores. Para ello, comparte este código:',
        label_share: 'Compartir',
        share_statement: ' Si va a tener evaluadores, ¿quiere que esa persona vea el resultado?',
        title_share_results: 'Compartir resultados',
        label_share_results: 'Si estas de acuerdo en que tus evaluadores vean tu progreso, activa compartir resultados:',
        create_objective_success: 'Objetivo creado correctamente',
        save_objective_success: 'Objetivo guardado correctamente',
        save_objective_error: 'Process has failed',
        schedule_evaluations: 'Programar evaluaciones',
        achieve: 'Logro',
        label_consistent: 'Consistente',
        not_consistent: 'No Consistente',
        consistency: 'Consistencia',
        obs_achieved: 'Logrado',
        obs_not_achieved: 'No logrado',
        obs_not_evaluated: 'No evaluado',
        bottom_statement: 'Para que su progreso sea consistente, deben realizarse al menos el 75% de las evaluaciones programadas.',

        add_friend_code: 'Ingresar código de invitación',
        friend_code: 'Ingresar código de invitación',
        label_friend_code: 'Código de invitación',
        atention: 'Atención',
        label_atention: 'Atención y concentración',
        label_block: 'Bloqueo de pensamientos negativos',
        label_perception: 'Mejora de percepción',

        label_new_article_notification: 'Nuevo artículo disponible para leer',

        label_new_objective_from_habit: 'Convertir en objetivo de acción',

        label_notes: 'Notas',

        no_notes: 'No hay notas',
        label_never_show_again: 'No volver a mostrar',

        action_share_title: 'Evalúa mi progreso Infinite Power',
        action_share_message:
          'Te invito a evaluar mi progreso en Infinite Power! Descarga la aplicación y accede con el siguiente enlace: infinitepower://code',
        ready: 'listo',
        copy_code: 'Código copiado',
        evaluate: 'Evaluar',
        see_details: 'Ver detalles',
        spanish: 'Español',
        english: 'Inglés',
        note_created_successfully: 'Nota creada exitosamente',
        objective_evaluated_successfully: 'Objetivo evaluado exitosamente',
        note_created_successfully: 'Nota creada exitosamente',
        objective_updated_successfully: 'Objetivo actualizado exitosamente',
        yes: 'Si',
        no: 'No',
        no_date: 'Sin Fecha',
        required: 'Requerido',
        all_day: 'Todos los dias',
        guide_for_answers: 'Guía para respuestas',
        focusing_questionary: 'cuestionario de enfoque',
        no_data: 'Sin datos',
        block_negative_thoughts: 'Bloqueo de pensamientos negativos',
        atention_and_concentration: 'Atención y concentración',
        perception_improvement: 'Mejora de percepción',
        never: 'Nunca',
        almost_never: 'Casi Nunca',
        occasionally: 'Ocacionalmente',
        frequently: 'Frecuentemente',
        very_frequently: 'Muy Frecuentemente',
        send_response: 'Enviar Respuesta',
        accept: 'Aceptar',
        user_name: 'Nombre de Usuario',
        to_your_account: 'a tu cuenta',
        and_enjoy_all_the_advantages: 'Y disfruta de todas las ventajas que',
        offers_you: 'te ofrece',
        forget_password: 'Contraseña olvidada',
        sign_in: 'Registrarse',
        log_in: 'Iniciar Sesión',
        user_registered_successfully: 'Usuario registrado exitosamente',
        meditation_tips: 'Tips de meditación',
        action_tips: 'Tips de acción',
        answers_were_sended_successfully: 'Las respuestas fueron enviadas exitosamente',
        mental_focus: 'enfoque mental',
        i_am_ready: 'estoy listo',
        get_in_ready: 'prepárate',
        recording: 'grabando',
        playing: 'reproduciendo',
        habits: 'hábitos',
        habit: 'hábito',
        consecutive_successful_weeks: 'Semanas Exitosas Consecutivas',
        view_tips_on: 'ver consejos sobre',
        convert_to_habit: 'convertir en hábito',
        delete_phrase_warning: 'Desea eliminar la frase?',
        deleted_correctly: 'Eliminado correctamente',
        created_correctly: 'Creado correctamente',
        saved_correctly: 'Guardado correctamente',
        affirmation: 'afirmación',
        affirmation_saved_as_draft: 'Afirmación guardada como borrador. Graba el audio para reproducirla en tu rutina.',
        unexpected_error_recording: 'Error inesperado al grabar.',
        notice: 'aviso',
        habits_tips: 'consejos de hábitos',
        affirmations_categories: 'agregar afirmaciones',
        category: 'categoria',
        you_will_receive_a_reminder_at: 'Recibiras un recordatorio a las',
        select_time: 'seleccionar hora',
        confirm: 'confirmar',
        last_21_days: 'ultimos 21 dias',
        january: 'enero',
        february: 'febrero',
        march: 'marzo',
        april: 'abril',
        may: 'mayo',
        june: 'junio',
        july: 'julio',
        august: 'agosto',
        september: 'septiembre',
        october: 'octubre',
        november: 'noviembre',
        december: 'diciembre',
        focus: 'enfoque',
        today_activities: 'actividades hoy',
        info: 'info',
        day_resume: 'resumen del día',
        write_note: 'escribir nota',
        to: 'a',
        select_a_image: 'seleccionar una imagen',
        take_photo: 'tomar una foto',
        choose_from_library: 'elegir de libreria',
        choose: 'elegir',
        show_more_notes: 'ver más notas',
        show_less_notes: 'ver menos notas',
        write_a_final_comment_before_evaluate: 'Escribir comentario final',
        focus_test: 'test de enfoque',
        infinitepower_note: 'nota de infinite power',
        show_image: 'ver imagen',
        show_notes: 'ver notas',
        hide_notes: 'ocultar notas',
        today: 'hoy',
        achievement: 'logro',
        last_7_days_achievements: 'logros últimos 7 días',
        last_7_evaluations_achievements: 'logros últimas 7 evaluaciones',
        streak: 'racha',
        day_results_for_objective: 'resultados del día para el objetivo',
        objective_average_achievement: 'Promedio de logro del objetivo',
        default_evaluations: 'evaluaciones por defecto',
        evaluations_not_carried_out_are_considered_as_not_achieved: 'las evaluaciones no realizadas son consideradas como no logradas',
        my_routines: 'mis rutinas',
        evaluations_all_days: 'evaluaciones todos los días.',
        evaluate_all_days: 'evalúo todos los días.',
        all_days: 'todos los días',
        evaluate: 'evalúo',
        on: 'los',
        evaluations: 'evaluaciones',
        achievements: 'logros',
        current_streak: 'racha actual',
        historical_streak: 'racha histórica',
        how_they_evaluated_me: 'cómo me evaluaron',
        objective_defined_at: 'objetivo definido el',
        day: 'día',
        days: 'días',
        active: 'activo',
        friends_objectives: 'objetivos de amigos',
        pick_a_date: 'escoja una fecha',
        days_left: 'faltan $days dias',
        pick_a_time: 'escoja un tiempo',
        the_field_is_required: 'el campo es requerido',
        objective_title: 'título de objetivo',
        objective_description: 'descripción del objetivo',
        objective_description_placeholder:
          'Este campo es opcional. Puedes utilizarlo para describir el objetivo con más detalle o sus beneficios o en qué o quién te inspiraste para definirlo',
        habit_trigger_to_replace: 'disparador del hábito a reemplazar',
        trigger_placeholder:
          'Campo opcional. Los hábitos que quieres reemplazar tienen un desencadenante que lo activa. Identificarlo aumenta tus posibilidades de eliminarlo',
        limit_date: 'Fecha límite',
        evaluation_days: 'Dias de evaluación',
        evaluators: 'evaluators',
        evaluation_days_reminder: 'Recordatorio los días de autoevaluación',
        confirmation: 'confirmación',
        are_you_sure_about_delete: 'está seguro de que desea proceder con la eliminación?',
        code: 'código',
        enter_code: 'ingresar código',
        unfollowed_correctly: 'dejado de seguir correctamente',
        reject: 'rechazar',
        invitation: 'invitación',
        has_invited_you_to_evaluate_the_objective: 'te ha invitado para evaluar el objetivo',
        objective_added_for_evaluation: 'objetivo agregado para evaluar',
        you_are_already_a_evaluator: 'ya estas evaluando el objetivo',
        date_for: 'correspondientes al',
        belt_info_title: 'consecutive weeks achieved',
        belt_info_title1: 'consecutive successful weeks',
      },
    }
  }
}

export default new Language()
